
; Interrupt ISR for the syscalls (0x80)
.INTERRUPTS_SYSCALLS:

    PUSH %eax ; save eax
    
    ; switch from interrupt stack to kernel stack

    MOV %esp, %eax

    MOV $CONST_OS_CURRENT_PCB_POINTER, %ecx

    MOV *%ecx, %ecx ; pcb pointer
    ADD $CONST_OS_PCB_KERNEL_STACK_TOP_OFFSET, %ecx
    MOV %ecx, %esp ; switch stack pointer

    ADD $12, %eax   ; pointer to old esp
    PUSH *%eax       ; push old esp

    SUB $4, %eax    ; pointer to old eflags
    PUSH *%eax       ; push old eflags

    SUB $4, %eax    ; pointer to old eip
    PUSH *%eax       ; push old eip

    SUB $4, %eax    ; pointer to old eax
    MOV *%eax, %eax ; resore eax

    ; kernel stack set up

    ; now jump to the right syscall handler

    CMP $CONST_SYSCALL_FILE_READ, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_READ
    CALL SYSCALLS_FILE_READ_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_READ:

    CMP $CONST_SYSCALL_FILE_WRITE, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_WRITE
    CALL SYSCALLS_FILE_WRITE_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_WRITE:

    CMP $CONST_SYSCALL_FILE_OPEN, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_OPEN
    CALL SYSCALLS_FILE_OPEN_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_OPEN:

    CMP $CONST_SYSCALL_FILE_CLOSE, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_CLOSE
    CALL SYSCALLS_FILE_CLOSE_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_CLOSE:

    CMP $CONST_SYSCALL_FILE_STAT, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_STAT
    CALL SYSCALLS_FILE_STAT_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_STAT:

    CMP $CONST_SYSCALL_FILE_SEEK, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_SEEK
    CALL SYSCALLS_FILE_SEEK_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_SEEK:

    CMP $CONST_SYSCALL_FILE_CREATE, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_CREATE
    CALL SYSCALLS_FILE_CREATE_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_CREATE:

    CMP $CONST_SYSCALL_FILE_DELETE, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_DELETE
    CALL SYSCALLS_FILE_DELETE_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_FILE_DELETE:

    CMP $CONST_SYSCALL_PROCESS_CREATE, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_PROCESS_CREATE
    CALL SYSCALLS_PROCESS_CREATE_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_PROCESS_CREATE:

    CMP $CONST_SYSCALL_PROCESS_EXIT, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_PROCESS_EXIT
    CALL SYSCALLS_PROCESS_EXIT_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_PROCESS_EXIT:

    CMP $CONST_SYSCALL_PROCESS_YIELD, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_PROCESS_YIELD
    CALL SYSCALLS_PROCESS_YIELD_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_PROCESS_YIELD:

    CMP $CONST_SYSCALL_TIMER_START, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_TIMER_START
    CALL SYSCALLS_TIMER_START_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_TIMER_START:

    CMP $CONST_SYSCALL_CONSOLE_PRINT_NUMBER, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_CONSOLE_PRINT_NUMBER
    CALL SYSCALLS_CONSOLE_PRINT_NUMBER_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_CONSOLE_PRINT_NUMBER:

    CMP $CONST_SYSCALL_CONSOLE_READ_NUMBER, %eax
    JNE _INTERRUPTS_SYSCALLS_SKIP_SYSCALL_CONSOLE_READ_NUMBER
    CALL SYSCALLS_CONSOLE_READ_NUMBER_WITH_ASSERTS
    JMP _INTERRUPTS_SYSCALLS_END_SYSCALL
    ._INTERRUPTS_SYSCALLS_SKIP_SYSCALL_CONSOLE_READ_NUMBER:

    ; invalid syscall
    ; terminat the process
    CALL SYSCALLS_PROCESS_EXIT

    ._INTERRUPTS_SYSCALLS_END_SYSCALL:
    IRET

; collect all the syscall handlers here

    .INCLUDE "os/src/interrupts/syscalls/process/create"
    .INCLUDE "os/src/interrupts/syscalls/process/exit"
    .INCLUDE "os/src/interrupts/syscalls/process/yield"

    .INCLUDE "os/src/interrupts/syscalls/file/close"
    .INCLUDE "os/src/interrupts/syscalls/file/create"
    .INCLUDE "os/src/interrupts/syscalls/file/delete"
    .INCLUDE "os/src/interrupts/syscalls/file/open"
    .INCLUDE "os/src/interrupts/syscalls/file/read"
    .INCLUDE "os/src/interrupts/syscalls/file/seek"
    .INCLUDE "os/src/interrupts/syscalls/file/stat"
    .INCLUDE "os/src/interrupts/syscalls/file/write"
    .INCLUDE "os/src/interrupts/syscalls/file/console_print_number"
    .INCLUDE "os/src/interrupts/syscalls/file/console_read_number"
    
    .INCLUDE "os/src/interrupts/syscalls/timer/start"

