import { app, BrowserWindow, dialog, ipcMain, IpcMainInvokeEvent, Menu, shell } from 'electron';
import * as path from 'path';
import { NumberSystems } from '../types/enumerations/NumberSystems';
import { Byte } from './../types/binary/Byte';
import { DoubleWord } from './../types/binary/DoubleWord';
import { SimulationController } from './simulator/SimulationController';
import appIcon from './../../assets/icons/app/icon.png';
import { PageNumber } from './../types/binary/PageNumber';
import fs from "node:fs";
import { InterruptNumbers } from '../types/enumerations/InterruptNumbers';
import { PageTableEntry } from '../types/binary/PageTableEntry';
import { PhysicalAddress } from '../types/binary/PhysicalAddress';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let mainWindow: BrowserWindow;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require('electron-squirrel-startup')) {
	app.quit();
}

if (process.env.NODE_ENV !== "test") {

app.setAppUserModelId("de.hs-hannover.IhmeCoreX1Simulator.IhmeCoreX1Simulator");

const buildMenu = (win: BrowserWindow, simulator: SimulationController): Menu => {
	const menu = Menu.buildFromTemplate([
		{
			label: "App",
			submenu: [
				{
					label: "Exit",
					accelerator: "CmdOrCtrl+Q",
					click() {
						app.quit()
					} 
				}
			]
		},
		{
			label: "File",
			submenu: [

				{
					label: "Open OS Home Folder",
					accelerator: "CmdOrCtrl+O",
					click() {
						shell.openPath(path.join(simulator.pathToOSFilesystem, "home"))
						.catch((err) => win.webContents.send("on_error", err));
					}
				},
				{
					label: "Assemble Program",
					accelerator: "CmdOrCtrl+A",
					click() {
						dialog.showOpenDialog({
							defaultPath: path.join(simulator.pathToOSFilesystem, "home"),
							properties: ["openFile", "createDirectory"],
							filters: [{ name: "Select Assembly File", extensions: ['asm'] }]
						}).then(function(fileObj) {
							if (!fileObj.canceled) {
								simulator.assembleProgram(fileObj.filePaths[0].replaceAll("\\", "/"));
								win.webContents.send("assembled_program", fileObj.filePaths[0]);
							}
						}).catch((err) => win.webContents.send("on_error", err))
					}				
				},
				{
					label: "Start Program",
					accelerator: "CmdOrCtrl+S",
					click() {
						dialog.showOpenDialog({
							defaultPath: path.join(simulator.pathToOSFilesystem, "bin"),
							properties: ["openFile", "createDirectory"],
							filters: [{ name: "Select Binary", extensions: ['bin'] }]
						}).then(function(fileObj) {
							if (!fileObj.canceled) {
								try {
									simulator.createProcess(fileObj.filePaths[0].replaceAll("\\", "/"));
									win.webContents.send("loaded_program", fileObj.filePaths[0]);
								} catch (e) {
									win.webContents.send("loaded_program", e);
								}
							}
						}).catch((err) => win.webContents.send("on_error", err))
					}	
				}
			],
		},
		{
			label: "Settings",
			submenu: [
				{
					label: "Behavior",
					submenu: [
						{
							label: "RAM",
							submenu : [
								{
									label: "Disable EIP Follow",
									click() {
										win.webContents.send("disable_ram_view_follow_eip");
									}
								},
								{
									label: "Enable EIP Follow",
									click() {
										win.webContents.send("enable_ram_view_follow_eip");
									}
								}
							]
						},
						{
							label: "Page Table",
							submenu : [
								{
									label: "Disable Auto Scroll",
									click() {
										if (simulator.autoScrollForPageTableEnabled) {
											win.webContents.send("disable_auto_scroll_page_table");
										}
									}
								},
								{
									label: "Enable Auto Scroll",
									click() {
										if (!simulator.autoScrollForPageTableEnabled) {
											win.webContents.send("enable_auto_scroll_page_table");
										}
									}
								}
							]
						},
						{
							label: "Output",
							submenu : [
								{
									label: "Logging",
									submenu : [
										{
											label: "Disable Logging",
											click() {
												win.webContents.send("hide_log");
											}
										},
										{
											label: "Enable Logging",
											click() {
												win.webContents.send("show_log");
											}
										}
									]
								},
								{
									label: "Console",
									submenu : [
										{
											label: "Disable Console",
											click() {
												win.webContents.send("hide_console");
											}
										},
										{
											label: "Enable Console",
											click() {
												win.webContents.send("show_console");
											}
										}
									]
								}
							]
						}
					]
				}
			]
		},
		{
			label: "Window",
			submenu: [
				{
					label: "Minimize",
					accelerator: "CmdOrCtrl+M",
					click() {
						if (win.isMinimizable() && !win.isMinimized()) {
							win.minimize();
						}
					}
				},
				{
					label: "Reload",
					accelerator: "CmdOrCtrl+R",
					click() {
						win.webContents.reload()
					}
				},
				{
					label: "Force Reload",
					accelerator: "CmdOrCtrl+Shift+R",
					click() {
						win.webContents.reloadIgnoringCache()
					}
				},
				{
					label: "Toggle Developer Tools",
					accelerator: "CmdOrCtrl+Shift+I",
					click() {
						win.webContents.openDevTools();
					}
				}
			]
		},
		{
			label: "Help",
			submenu: [
				{
					label: "Documentation",
					click() {
						shell.openExternal("https://programmit.github.io/CPU-Simulator/")
					}
				},
				{
					label: "GitHub Repository",
					click() {
						shell.openExternal("https://github.com/ProgrammIt/CPU-Simulator")
					}
				}
			]
		}
	]);
	return menu;
};

const createWindow = (): void => {
	// Create the browser window.
	mainWindow = new BrowserWindow({
		height: 600,
		width: 800,
		webPreferences: {
			preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
		},
		icon: path.resolve(__dirname, appIcon),
	});

	// Open the DevTools.
	// mainWindow.webContents.openDevTools();

	let pathToLanguageDefinition: string;
	let pathToOSFilesystem: string;
	if (app.isPackaged) {
		pathToLanguageDefinition = path.join(process.resourcesPath, "settings", "language_definition.json");
		pathToOSFilesystem = path.join(app.getPath("userData"), "os_filesystem");

		const pathToVersionFile = path.join(app.getPath("userData"), "version");
		const currentVersion = app.getVersion();

		if (!fs.existsSync(pathToVersionFile)) {
			fs.writeFileSync(pathToVersionFile, currentVersion, "utf8");
		}

		if (fs.readFileSync(pathToVersionFile, "utf8").trim() !== currentVersion || !fs.existsSync(pathToOSFilesystem)) {
			fs.writeFileSync(pathToVersionFile, currentVersion, "utf8");

			if (!fs.existsSync(pathToOSFilesystem)) {
				fs.mkdirSync(pathToOSFilesystem);
			}

			const pathToIntenalOSFilesystem =  path.join(process.resourcesPath, "os_filesystem");

			if (!fs.existsSync(path.join(pathToOSFilesystem, "home"))) {
				fs.cpSync(path.join(pathToIntenalOSFilesystem, "home"), path.join(pathToOSFilesystem, "home"), { recursive: true });
			}

			if (!fs.existsSync(path.join(pathToOSFilesystem, "bin"))) {
				fs.mkdirSync(path.join(pathToOSFilesystem, "bin"));
			}

			fs.cpSync(path.join(pathToIntenalOSFilesystem, "os"), path.join(pathToOSFilesystem, "os"), { recursive: true });
		}
	} else {
		pathToLanguageDefinition = path.join(process.cwd(), "settings", "language_definition.json");
		pathToOSFilesystem = path.join(process.cwd(), "os_filesystem");
	}
	
	const simulator = SimulationController.getInstanceOrCreate(
		DoubleWord.SIZE,
		pathToLanguageDefinition,
		pathToOSFilesystem,
		!app.isPackaged
	);
	
	registerHandlers(simulator, mainWindow);

	// Set the menu bar.
	const menu = buildMenu(mainWindow, simulator);
	Menu.setApplicationMenu(menu);

	// and load the index.html of the app.
	mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

const registerHandlers = (simulator: SimulationController, win: BrowserWindow): void => {
	ipcMain.on('get-preload-path', (e) => {
		e.returnValue = MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY;
	});
	
	ipcMain.removeHandler("readRangeFromPhysicalMemory");
	ipcMain.handle("readRangeFromPhysicalMemory", async (event: Electron.IpcMainInvokeEvent, fromPhysicalAddress: DoubleWord, toPhysicalAddress: DoubleWord): Promise<Map<DoubleWord, Byte>> => {
		const tmp: Map<DoubleWord, Byte> = new Map<DoubleWord, Byte>();
		for (let i = fromPhysicalAddress; i <= toPhysicalAddress; ++i) {
			const byte: Byte = simulator.mainMemory.readByteFrom(i);
			tmp.set(i, byte);
		}
		return tmp;
	});

	ipcMain.removeHandler("readFromPhysicalMemory");
	ipcMain.handle("readFromPhysicalMemory", async (event: Electron.IpcMainInvokeEvent, physicalAddress: DoubleWord): Promise<Byte > => {
		const byte: Byte = simulator.mainMemory.readByteFrom(physicalAddress);
		return byte;
	});

	ipcMain.removeHandler("readDoubleWordFromPhysicalMemory");
	ipcMain.handle("readDoubleWordFromPhysicalMemory", async (event: Electron.IpcMainInvokeEvent, physicalAddress: DoubleWord): Promise<DoubleWord> => {
		const doubleWord: DoubleWord = simulator.mainMemory.readDoublewordFrom(physicalAddress);
		return doubleWord;
	});

	ipcMain.removeHandler("findVirtualAddresses");
	ipcMain.handle("findVirtualAddresses", async (event: Electron.IpcMainInvokeEvent, physicalAddress: DoubleWord): Promise<DoubleWord[]> => {
		const virtualAddresses: DoubleWord[] = simulator.core.mmu.findVirtualFromPhysical(physicalAddress as PhysicalAddress) as DoubleWord[];
		return virtualAddresses;
	});

	ipcMain.removeHandler("translateVirtualAddress");
	ipcMain.handle("translateVirtualAddress", async (event: Electron.IpcMainInvokeEvent, virtualAddress: DoubleWord): Promise<DoubleWord> => {
		const physicalAddress: DoubleWord = simulator.core.mmu.translate(virtualAddress, false, false, true, true);
		return physicalAddress;
	});

	ipcMain.removeHandler("readRangeFromVirtualMemory");
	ipcMain.handle("readRangeFromVirtualMemory", async (event: Electron.IpcMainInvokeEvent, fromVirtualAddress: DoubleWord, toVirtualAddress: DoubleWord): Promise<Map<DoubleWord, Byte | undefined>> => {
		const tmp: Map<DoubleWord, Byte | undefined> = new Map<DoubleWord, Byte | undefined>();
		for (let i = fromVirtualAddress; i <= toVirtualAddress; ++i) {
			try {
				const physicalAddress:PhysicalAddress = simulator.core.mmu.translate(i, false, false, true, true);
				const byte: Byte = simulator.mainMemory.readByteFrom(physicalAddress);
				tmp.set(i, byte);
			}
			catch {
				tmp.set(i, undefined);
			}
		}
		return tmp;
	});

	ipcMain.removeHandler("readFromVirtualMemory");
	ipcMain.handle("readFromVirtualMemory", async (event: Electron.IpcMainInvokeEvent, virtualAddress: DoubleWord): Promise<Byte | undefined> => {
		try {
			const physicalAddress:PhysicalAddress = simulator.core.mmu.translate(virtualAddress, false, false, true, true);
			const byte: Byte = simulator.mainMemory.readByteFrom(physicalAddress);
			return byte;
		} catch {
			return undefined;
		}
		
	});

	ipcMain.removeHandler("readPageTableEntries");
	ipcMain.handle("readPageTableEntries", async (event: Electron.IpcMainInvokeEvent, firstPageNumberToRead: PageNumber, lastPageNumberToRead: PageNumber): Promise<Map<PageNumber, PageTableEntry>> => {
		const tmp: Map<PageNumber, PageTableEntry> = new Map<PageNumber, PageTableEntry>();
		const fromPhysicalAddressDec: number = firstPageNumberToRead + simulator.core.ptp.content;
		const toPhysicalAddressDec: number = lastPageNumberToRead + simulator.core.ptp.content;
		let currentPageFrameNumber: PageNumber = firstPageNumberToRead;
		let currentPhysicalAddressDec: number = fromPhysicalAddressDec;
		while (currentPhysicalAddressDec <= toPhysicalAddressDec) {
			const pageTableEntry: PageTableEntry = simulator.mainMemory.readDoublewordFrom(PhysicalAddress.fromNumber(currentPhysicalAddressDec)) as PageTableEntry;
			tmp.set(currentPageFrameNumber, pageTableEntry);
			currentPhysicalAddressDec += 4;
			currentPageFrameNumber++;
		}
		return tmp;
	});

	ipcMain.removeHandler("readEAX");
	ipcMain.handle("readEAX", async (event: IpcMainInvokeEvent, basis: NumberSystems): Promise<string> => {
		const content: DoubleWord = simulator.core.eax.content;
		let result: string;
		if (basis === NumberSystems.HEX) {
			result = `0x${content.toString(16)}`;
		} else if (basis === NumberSystems.DEC) {
			result = `${content}`;
		} else {
			result = content.toString(2).padStart(32, "0").replace(/(.{4})/g, "$1 ").trim();
		}
		return result;
	});

	ipcMain.removeHandler("readEBX");
	ipcMain.handle("readEBX", async (event: IpcMainInvokeEvent, basis: NumberSystems): Promise<string> => {
		const content: DoubleWord = simulator.core.ebx.content;
		let result: string;
		if (basis === NumberSystems.HEX) {
			result = `0x${content.toString(16)}`;
		} else if (basis === NumberSystems.DEC) {
			result = `${content}`;
		} else {
			result = content.toString(2).padStart(32, "0").replace(/(.{4})/g, "$1 ").trim();
		}
		return result;
	});

	ipcMain.removeHandler("readECX");
	ipcMain.handle("readECX", async (event: IpcMainInvokeEvent, basis: NumberSystems): Promise<string> => {
		const content: DoubleWord = simulator.core.ecx.content;
		let result: string;
		if (basis === NumberSystems.HEX) {
			result = `0x${content.toString(16)}`;
		} else if (basis === NumberSystems.DEC) {
			result = `${content}`;
		} else {
			result = content.toString(2).padStart(32, "0").replace(/(.{4})/g, "$1 ").trim();
		}
		return result;
	});

	ipcMain.removeHandler("readEDX");
	ipcMain.handle("readEDX", async (event: IpcMainInvokeEvent, basis: NumberSystems): Promise<string> => {
		const content: DoubleWord = simulator.core.edx.content;
		let result: string;
		if (basis === NumberSystems.HEX) {
			result = `0x${content.toString(16)}`;
		} else if (basis === NumberSystems.DEC) {
			result = `${content}`;
		} else {
			result = content.toString(2).padStart(32, "0").replace(/(.{4})/g, "$1 ").trim();
		}
		return result;
	});

	ipcMain.removeHandler("readEIP");
	ipcMain.handle("readEIP", async (event: IpcMainInvokeEvent, basis: NumberSystems): Promise<string> => {
		const content = simulator.core.eip.content;
		let result: string;
		if (basis === NumberSystems.HEX) {
			result = `0x${content.toString(16)}`;
		} else if (basis === NumberSystems.DEC) {
			result = `${content}`;
		} else {
			result = content.toString(2).padStart(32, "0").replace(/(.{4})/g, "$1 ").trim();
		}
		return result;
	});

	ipcMain.removeHandler("readFLAGS");
	ipcMain.handle("readFLAGS", async (): Promise<string> => {
		const content = simulator.core.flags.content;
		return content.toString(2).padStart(8, "0");
	});

	ipcMain.removeHandler("readEIR");
	ipcMain.handle("readEIR", async (event: IpcMainInvokeEvent, asInstruction: boolean): Promise<string> => {
		if (asInstruction) {
			// TODO
		}
		const content = simulator.core.eir.content;
		return content.toString(2).padStart(32, "0").replace(/(.{4})/g, "$1 ").trim();
	});

	ipcMain.removeHandler("readNPTP");
	ipcMain.handle("readNPTP", async (event: IpcMainInvokeEvent, basis: NumberSystems): Promise<string> => {
		const content = simulator.core.nptp.content;
		let result: string;
		if (basis === NumberSystems.HEX) {
			result = `0x${content.toString(16)}`;
		} else if (basis === NumberSystems.DEC) {
			result = `${content}`;
		} else {
			result = content.toString(2).padStart(32, "0").replace(/(.{4})/g, "$1 ").trim();
		}
		return result;
	});

	ipcMain.removeHandler("readVMPTR");
	ipcMain.handle("readVMPTR", async (event: IpcMainInvokeEvent, basis: NumberSystems): Promise<string> => {
		const content = simulator.core.vmtpr.content;
		let result: string;
		if (basis === NumberSystems.HEX) {
			result = `0x${content.toString(16)}`;
		} else if (basis === NumberSystems.DEC) {
			result = `${content}`;
		} else {
			result = content.toString(2).padStart(32, "0").replace(/(.{4})/g, "$1 ").trim();
		}
		return result;
	});

	ipcMain.removeHandler("readESP");
	ipcMain.handle("readESP", async (event: IpcMainInvokeEvent, basis: NumberSystems): Promise<string> => {
		const content = simulator.core.esp.content;
		let result: string;
		if (basis === NumberSystems.HEX) {
			result = `0x${content.toString(16)}`;
		} else if (basis === NumberSystems.DEC) {
			result = `${content}`;
		} else {
			result = content.toString(2).padStart(32, "0").replace(/(.{4})/g, "$1 ").trim();
		}
		return result;
	});

	ipcMain.removeHandler("readITP");
	ipcMain.handle("readITP", async (event: IpcMainInvokeEvent, basis: NumberSystems): Promise<string> => {
		const content = simulator.core.itp.content;
		let result: string;
		if (basis === NumberSystems.HEX) {
			result = `0x${content.toString(16)}`;
		} else if (basis === NumberSystems.DEC) {
			result = `${content}`;
		} else {
			result = content.toString(2).padStart(32, "0").replace(/(.{4})/g, "$1 ").trim();
		}
		return result;
	});

	ipcMain.removeHandler("readGPTP");
	ipcMain.handle("readGPTP", async (event: IpcMainInvokeEvent, basis: NumberSystems): Promise<string> => {
		if (simulator.core.gptp === null) {
			return "-";
		}
		const content = simulator.core.gptp.content;
		let result: string;
		if (basis === NumberSystems.HEX) {
			result = `0x${content.toString(16)}`;
		} else if (basis === NumberSystems.DEC) {
			result = `${content}`;
		} else {
			result = content.toString(2).padStart(32, "0").replace(/(.{4})/g, "$1 ").trim();
		}
		return result;
	});

	ipcMain.removeHandler("readPTP");
	ipcMain.handle("readPTP", async (event: IpcMainInvokeEvent, basis: NumberSystems): Promise<string> => {
		const content = simulator.core.ptp.content;
		let result: string;
		if (basis === NumberSystems.HEX) {
			result = `0x${content.toString(16)}`;
		} else if (basis === NumberSystems.DEC) {
			result = `${content}`;
		} else {
			result = content.toString(2).padStart(32, "0").replace(/(.{4})/g, "$1 ").trim();
		}
		return result;
	});

	ipcMain.removeHandler("nextCycle");
	ipcMain.handle("nextCycle", async (): Promise<void> => {
		try {
			simulator.core.cycle();
		} catch (error) {
			if (error instanceof Error) {
				win.webContents.send("error", error.message);
			}
		}
	});

	ipcMain.removeHandler("on_disable_auto_scroll_page_table");
	ipcMain.handle("on_disable_auto_scroll_page_table", async (): Promise<void> => {
		simulator.autoScrollForPageTableEnabled = false;
		return;
	});

	ipcMain.removeHandler("on_enable_auto_scroll_page_table");
	ipcMain.handle("on_enable_auto_scroll_page_table", async (): Promise<void> => {
		simulator.autoScrollForPageTableEnabled = true;
		return;
	});

	ipcMain.removeHandler("keyboard_interrupt");
	ipcMain.on("keyboard_interrupt", async (event: IpcMainInvokeEvent, consoleInput: string): Promise<void> => {
		simulator.core.fs.pushStdinBuffer(consoleInput)
		simulator.core.triggertExternalInterrupt(InterruptNumbers.KEYBOARD);
		return;
	})

};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
	try {
		createWindow();
	}
	catch (e) {
		console.log(e);
	}
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') {
		app.quit();
	}
});

app.on('activate', () => {
	// On OS X it's common to re-create a window in the app when the
	// dock icon is clicked and there are no other windows open.
	if (BrowserWindow.getAllWindows().length === 0) {
		createWindow();
	}
});

}

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

export function getMainWindow(): BrowserWindow | undefined {
	return mainWindow;
}
