export enum InterruptNumbers {
    DIVIDE_ERROR = 0x0,
	INVALID_OPCODE = 0x6,
	GENERAL_PROTECTION_FAULT = 0xD,
	PAGE_FAULT = 0xE,
	TIMER = 0x20,
	PERIODIC_TIMER = 0x21,
	SYSTEM_CALL = 0x80,
	KEYBOARD = 0x81,
}