/**
 * An enum representing the available operand types and their binary codes.
 * @author Erik Burmester <erik.burmester@nextbeam.net>
 */
export enum OperandTypeCodes {
	NO = 0b0000000,
	IMMEDIATE = 0b1010000,
	REGISTER = 0b1100000,
	MEMORY_ADDRESS = 0b1110000
}

export enum OperandTypeNames {
	REGISTER_INDIRECT = "REGISTER_INDIRECT",
	REGISTER_DIRECT = "REGISTER_DIRECT",
	IMMEDIATE_HEXADECIMAL = "IMMEDIATE_HEXADECIMAL",
	IMMEDIATE_BINARY = "IMMEDIATE_BINARY",
	IMMEDIATE_DECIMAL = "IMMEDIATE_DECIMAL",
	MEMORY_ADDRESS_HEXADECIMAL = "MEMORY_ADDRESS_HEXADECIMAL",
	MEMORY_ADDRESS_BINARY = "MEMORY_ADDRESS_BINARY",
	MEMORY_ADDRESS_DECIMAL = "MEMORY_ADDRESS_DECIMAL",
	LABEL = "LABEL"
}