import { accessSync, chmodSync, constants, existsSync, lstatSync, openSync, readSync, unlinkSync, writeFileSync, writeSync } from 'node:fs';
import { FilesystemError } from '../../types/errors/FilesystemError';
import { DoubleWord } from '../../types/binary/DoubleWord';
import { applicationWindow } from '../../main';

class VirtualFileDescriptor {
    public filename: string;
    public virtual_fd: number;
    public real_fd: number;
    public seek_position: number = 0;
    constructor(filename: string, virtual_fd: number, real_fd: number) {
        this.filename = filename;
        this.virtual_fd = virtual_fd;
        this.real_fd = real_fd;
    }
}

export class PassthroughFilesystem {
    private path: string;
    public fd_map = new Map<number, VirtualFileDescriptor>(); // keys are the virtual file descriptors (generated by increamenting fd_counter)
    private fd_counter: number = 1;
    private stdin_console_buffer: Uint8Array[] = [];
    constructor(path: string) {
        // Perform basic tests to check whether the directory is available
        if (path == "/") {
            throw new FilesystemError("Filesystem path should not be the root directory (/)");
        }
        if (path == "") {
            // Use working directory as fallback
            path = ".";
        }
        if (!path.endsWith("/")) {
            path += "/"
        }
        if (!existsSync(path)) {
            throw new FilesystemError(path + " does not exist.")
        }
        accessSync(path, constants.R_OK | constants.W_OK);
        this.path = path;
    }

    public io_seek(fd: number, offset: number, mode: number): number {
        if (!this.fd_map.has(fd)) {
            // invalid fd
            return -1;
        }
        const vfd = this.fd_map.get(fd)!

        let new_seek_postion = 0;
        switch (mode) {
            case 0: // 0 - Seek from current position
                new_seek_postion = vfd.seek_position + offset;
                break;
            case 1: // 1 - Seek from start of file
                new_seek_postion = offset;
                break;
            case 2: // 2 - Seek from end of file
                this.file_stat(vfd.filename)
                // TODO error handling if file_stat fails due to race condition
                new_seek_postion = this.file_stat(vfd.filename) - offset;
                break;
            default:
                // unkown mode
                return -4;
        }

        if (this.file_stat(vfd.filename) < vfd.seek_position) {
            // seek position out of bounds
            return -2;
        }
        if (vfd.seek_position + offset < 0) {
            // negative seek position
            return -3;
        }
        // node:fs doesnt support seek() on file descriptors, but allows it on write commands. Seek is emulated on each write command.
        vfd.seek_position += new_seek_postion;
        return 0;
    }

    public io_close(fd: number): number {
        if (!this.fd_map.has(fd)) {
            // invalid fd
            return -1;
        }
        this.fd_map.delete(fd);
        return 0;
    }

    public io_read_buffer(fd: number, buffer: DataView, size: number): number {
        if (fd != 0) {
            if (!this.fd_map.has(fd)) {
                // invalid fd
                return -1;
            }
            const vfd = this.fd_map.get(fd)!
            if (this.file_stat(vfd.filename) < vfd.seek_position) {
                // invalid seek position
                return -2;
            }

            return readSync(vfd.real_fd, buffer, 0, size, vfd.seek_position)
        } else {
            // fd=0 -> console input
            if (this.stdin_console_buffer.length === 0) {
                // no console input ready
                return -3;
            }
            let current: Uint8Array; 
            let stdin_console_buffer_index: number = 0;
            let stringFound: boolean = false;
            const utf8Decoder = new TextDecoder('UTF-8');
            
            //Uses the first string buffer as current buffer, if none is found, then fall back to using number input as string buffer.
            while (stdin_console_buffer_index < this.stdin_console_buffer.length) {
                const line = this.stdin_console_buffer[stdin_console_buffer_index];
                const num = Number(utf8Decoder.decode(line));
                if (isNaN(num)) {
                    stringFound = true;
                    break;
                }
                ++stdin_console_buffer_index;
            }

            if (stringFound) {
                current = this.stdin_console_buffer[stdin_console_buffer_index];
            } else {
                current = this.stdin_console_buffer[0];
                stdin_console_buffer_index = 0;
            }
            
            const input_len = current.length;
            let bytes_read = 0;
            while (input_len > bytes_read && size > bytes_read) {
                buffer.setUint8(bytes_read, current[bytes_read]);
                bytes_read++
            }
            if (bytes_read === input_len) {
                // read all characters from the line, remove it from the used buffer list
                this.stdin_console_buffer.splice(stdin_console_buffer_index, 1);
            } else {
                // not all characters from the stdin buffer have been read because the buffer from the OS was too small
                // remove the characters that have been read
                this.stdin_console_buffer[stdin_console_buffer_index] = current.slice(bytes_read);
            }
            return bytes_read;
        }
        
    }

    public io_write_buffer(fd: number, buffer: DataView, size: number): number {
        if (fd != 0) {
           if (!this.fd_map.has(fd)) {
                // invalid fd
                return -1;
            }
            const vfd = this.fd_map.get(fd)!
            if (this.file_stat(vfd.filename) < vfd.seek_position) {
                // invalid seek position
                return -2;
            }

            const bytes_written: number = writeSync(vfd.real_fd, buffer, 0, size, vfd.seek_position);
            vfd.seek_position += bytes_written;
            return bytes_written;
        } else {
            // fd=0 -> console output
            applicationWindow.mainWindow?.webContents.send('update_console', new TextDecoder('UTF-8').decode(buffer));
            return buffer.byteLength;
        }
    }

    public file_create(filename: string) {
        const path = this.path + filename
        if (existsSync(path)) {
            // file does already exist
            return -1;
        }
        writeFileSync(path, "", {mode: 0o777, flag: "w+"})
        chmodSync(path, 0o777)
        return 0;
    }

    public file_delete(filename: string): number {
        const path = this.path + filename
        if (!existsSync(path)) {
            // file does not exist
            return -1;
        }
        unlinkSync(path)
        return 0;
    }

    public file_open(filename: string): number {
        if (this.file_stat(filename) < 0) {
            return -1;
        }
        const path = this.path + filename
        const real_fd = openSync(path, "r+", constants.O_RDWR);
        const vfd = new VirtualFileDescriptor(filename, this.fd_counter++, real_fd);
        this.fd_map.set(vfd.virtual_fd, vfd);
        return vfd.virtual_fd;
    }

    public file_stat(filename: string): number {
        const path = this.path + filename;
        if (!existsSync(path)) {
            // file does not exist
            return -1;
        }
        const stat = lstatSync(path)
        if (!stat.isFile() || stat.isDirectory()) {
            // not a file
            return -2;
        }
        return stat.size;
    }

    public console_print_number(num: number) {
        const signedNumber: number = num | 0;
        applicationWindow.mainWindow?.webContents.send('update_console', signedNumber.toString(10));
    }

    public console_read_number(): [number, number] {
        if (this.stdin_console_buffer.length === 0) {
            // error -1 -> no input ready
            return [0, -1];
        }

        let stdin_console_buffer_index = 0;

        const utf8Decoder = new TextDecoder('UTF-8');

        let num: number = NaN;
        while (stdin_console_buffer_index < this.stdin_console_buffer.length) {
            const line = this.stdin_console_buffer[stdin_console_buffer_index];
            num = Number(utf8Decoder.decode(line));
            if (!isNaN(num)) {
                break;
            }
            ++stdin_console_buffer_index;
        }

        if (isNaN(num)) {
            // error -2 -> could not parse number
            return [0, -2];
        }
        if (num > DoubleWord.MAX_POSITIVE_NUMBER || num < DoubleWord.MAX_NEGATIVE_NUMBER) {
            // error -2 -> number does not fit into 32 bit DoubleWord
            this.stdin_console_buffer.splice(stdin_console_buffer_index, 1);
            return [0, -3]
        }
        this.stdin_console_buffer.splice(stdin_console_buffer_index, 1);
        return [num, 0];
    }

    /**
     * This method converts a string into a Uint8Array and adds it to the internal io buffer.
     * If the io buffer gets bigger than 20 entries, then the oldest entry gets removed.
     * @param line String from the console that gets added to the internal io buffer.
     */
    public pushStdinBuffer(line: string): void {
        const utf8Encoder = new TextEncoder();
        const encodedString: Uint8Array = utf8Encoder.encode(line);
        if (this.stdin_console_buffer.length > 255) {
            this.stdin_console_buffer.shift();
        }
        this.stdin_console_buffer.push(encodedString);
    }

    /**
     * This method counts how many strings are currently in the input buffer.
     * Since numbers are also counted as strings, the function just returns the size of the input buffer.
     * @returns The number of strings that are currently in the input buffer.
     */
    public getStdinBufferStringCount(): number {
        return this.stdin_console_buffer.length;
    }

    /**
     * This method counts how many numbers are currently in the input buffer.
     * @returns The amount of numbers in the input buffer.
     */
    public getStdinBufferNumberCount(): number {
        if (this.stdin_console_buffer.length === 0) {
            return 0;
        }

        let stdin_console_buffer_index = 0;
        let numberCount: number = 0;
        const utf8Decoder = new TextDecoder('UTF-8');

        while (stdin_console_buffer_index < this.stdin_console_buffer.length) {
            let num: number = NaN;
            const line = this.stdin_console_buffer[stdin_console_buffer_index];
            num = Number(utf8Decoder.decode(line));
            if (!isNaN(num)) {
                ++numberCount;
            }
            ++stdin_console_buffer_index;
        }
        return numberCount;
    }
}